export type GlossaryEntry = {
  term: string;
  definition: string;
};

// Rulebook-aligned glossary terms.
export const glossaryEntries: GlossaryEntry[] = [
  { term: "Bamboos (Bams/Boos)", definition: "One of three suits. Red bamboos: 1, 5, 7, 9. Green bamboos: 2, 3, 4, 6, 8." },
  { term: "Big Card (Mahjong GITA)", definition: "South round option where East chooses one hand and all four players attempt the same hand." },
  { term: "Bonus Tiles", definition: "The 8 flowers and seasons. Usually replaced from the flower wall when drawn." },
  { term: "Bouquet", definition: "High-value flower combination used for bonus points and/or doubles." },
  { term: "Buying", definition: "Taking a discard from the player on your left. Allowed only in South round (table rules may vary)." },
  { term: "Charleston / Tic-Tac / Dotting", definition: "Compulsory tile exchange phase before East's first discard in South/West rounds." },
  { term: "Characters (Cracks/Craks)", definition: "One of the three numbered suits in Mahjong." },
  { term: "Chow (Run)", definition: "Three consecutive tiles in the same suit. Can be claimed only from the player on your left." },
  { term: "Clean Hand", definition: "A valid hand that meets clean/doubles conditions and can receive count-based payout." },
  { term: "Concealed Hand", definition: "Hand built from self-picked (and allowed bought) tiles, not exposed from discards." },
  { term: "Corresponding Dragons (CD)", definition: "Rulebook linkage of dragons to suits (used in card-based and advanced hands)." },
  { term: "Crochet", definition: "Three tiles of the same number across three suits." },
  { term: "Dead Hand", definition: "A player disqualified from winning after a wrong declaration; play continues." },
  { term: "Dealer (East)", definition: "East seat. East starts play and gives/gets double in scoring." },
  { term: "Dots / Rings / Circles", definition: "One of three numbered suits in Mahjong." },
  { term: "Double Limit", definition: "A scoring level above full limit, commonly 2000 (or 4000 when East is involved)." },
  { term: "Doubles", definition: "Scoring multipliers from hand patterns, flowers, winds, dragons, and special conditions." },
  { term: "East Passport", definition: "East-round style where only specific approved combinations are valid." },
  { term: "Exposed Hand", definition: "Hand using called/claimed tiles shown face-up on the table." },
  { term: "Flower Wall", definition: "Section of wall used for flower replacement and kong replacement draws." },
  { term: "GRW", definition: "One of each dragon: Green, Red, and White. Used in specific valid hands (e.g. East passport)." },
  { term: "Goulash", definition: "West round format: no buying, no chows/runs, no crochet/knit, minimum doubles required." },
  { term: "Heads and Tails", definition: "Terminal-focused hand using 1s and 9s; often treated as a high-value/doubles hand." },
  { term: "Honours", definition: "Dragons and winds tiles (RGW + NEWS)." },
  { term: "Indian Traditional", definition: "The 4-round format covered here: East, South, West, North." },
  { term: "Knit", definition: "Two tiles with the same number across two suits; round-specific constraints apply." },
  { term: "Kitty", definition: "Pot funded by players in Goulash after draw conditions. Claimed by outright winner." },
  { term: "Kong", definition: "Four identical tiles. Requires replacement draw from flower/garden wall." },
  { term: "Majors", definition: "Honours plus terminals (1s and 9s)." },
  { term: "Mahjong", definition: "Winning declaration when hand is complete under the active round rules." },
  { term: "Minors", definition: "Numbered suit tiles from 2 to 8." },
  { term: "Mixed Chow", definition: "Number sequence spread across suits (round-specific validity)." },
  { term: "NEWS", definition: "North, East, West, South winds combination used in specific valid hands." },
  { term: "Own Flower Pair", definition: "Flower pair matching your seat wind; receives bonus points." },
  { term: "Pair", definition: "Two identical tiles. A standard winning hand includes exactly one pair." },
  { term: "Penalty", definition: "Payment consequence for specific errors (e.g., wrongful give/call situations)." },
  { term: "Prevailing Wind", definition: "Current round wind (East, South, West, North)." },
  { term: "Pung", definition: "Three identical tiles. Can be claimed from any player discard." },
  { term: "Qwong", definition: "Five-of-a-kind style set used in advanced/joker-capable hands." },
  { term: "Rack / Racking", definition: "Placing drawn tile on your rack before discard; helps prevent late-call disputes." },
  { term: "Real Bouquet", definition: "Own flower pair + round flower pair; high bonus payout (often 1000)." },
  { term: "Round Flower Pair", definition: "Flower pair matching the current prevailing wind; receives bonus points." },
  { term: "Scoring Sticks", definition: "Point chips/sticks typically 100, 500, 1000, 2000, and 5000." },
  { term: "Seasons", definition: "Four bonus tiles paired with directions 1-4, similar to flowers." },
  { term: "Seat Wind", definition: "Your current table direction (East, South, West, North)." },
  { term: "Small Cards", definition: "South-round option where each player draws a different target hand card." },
  { term: "Super Limit", definition: "High scoring tier above double limit (commonly 4000)." },
  { term: "Table Calling", definition: "Claiming from table discards; availability depends on card/round rules." },
  { term: "Table Rule", definition: "House rule agreed before play (caps, exchange details, payout variants)." },
  { term: "Terminals", definition: "Tiles numbered 1 and 9 in each suit." },
  { term: "Top Limit", definition: "Highest standard limit tier (commonly 10000)." },
  { term: "Wall Game", definition: "Drawn hand when wall is exhausted with no winner." },
  { term: "West Round (Goulash)", definition: "Third round focused on pungs/kongs and doubles-based scoring." },
  { term: "Wrong Declaration", definition: "Invalid Mahjong call; declaring player becomes dead hand." },
];
